# Global configuration file for GoLismero.
[golismero]

#------------------------------------------------------------------------------
# Main options
#------------------------------------------------------------------------------

# Default profile.
profile = default

# UI mode.
# This translates directly to the corresponding UI plugin.
ui_mode = console

# Verbosity level. May be one of the following values:
# 0: silent
# 1: normal
# 2: verbose
# 3: very verbose
verbose = 2

# Colorize console output.
color = yes

#------------------------------------------------------------------------------
# Audit options
#------------------------------------------------------------------------------

# SQLite connection string, in the form sqlite://filename
# When no filename is specified, the audit name is used.
audit_db = sqlite://

#------------------------------------------------------------------------------
# Network options
#------------------------------------------------------------------------------

# Maximum number of concurrent connections per host.
# Default value is platform dependent.
#max_connections = 20

# Use a persistent cache?
# The persistent cache is stored at: ~/.golismero/cache.db
# If you choose "no" the cached data is kept in memory.
use_cache_db = yes

#------------------------------------------------------------------------------
# Plugin options
#------------------------------------------------------------------------------

# Plugins folder.
#plugins_folder = ~/my_custom_golismero_plugins

# Plugin whitelist, comma separated.
# Use "all" to include all plugins.
enable_plugins = all

# Plugin blacklist, comma separated.
# Use "all" to disable all plugins.
#disable_plugins = attack, intrude

# Maximum number plugins to execute concurrently.
# Default value is platform dependent.
#max_concurrent = 20

# Plugin settings overrides follow.
#
# Use the following format:
#  * The section name must begin with the plugin ID. It can be the full ID
#    (testing/scan/openvas) or just the last part (openvas).
#  * If the section name is just the plugin ID, the options below override
#    the default argument values.
#  * To override other sections of the .golismero file, append the section name
#    to the plugin ID, separated by a colon (spider:Configuration).
#  * The [Core] and [Documentation] sections can't be overridden.
#
# Examples:
#
# # Using just the plugin ID, changes the arguments.
# [openvas]
# host = 192.168.56.101
#
# # Using the full plugin ID works exactly the same way.
# [testing/scan/openvas]
# user = my_openvas_user
# password = my s3cr3t p4ssw0rd
#
# # Changing stuff in the Configuration section.
# [spider : Configuration]
# wordlist_no_spider = my_custom_wordlist.txt
#
# # Changing stuff in any other section.
# [testing/scan/brute_suffixes : common_suffixes]
# w2 = an_extra_suffix_wordlist.txt
