Document: golismero
Title: Debian golismero Manual
Author: <insert document author here>
Abstract: This manual describes what golismero is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/golismero/golismero.sgml.gz

Format: postscript
Files: /usr/share/doc/golismero/golismero.ps.gz

Format: text
Files: /usr/share/doc/golismero/golismero.text.gz

Format: HTML
Index: /usr/share/doc/golismero/html/index.html
Files: /usr/share/doc/golismero/html/*.html
